### ISSUE TITLE
Attendees list and reserve event

### ISSUE THREAD

**Issue by yehiatarek63** [silverkeytech/reserve#10]
```[tasklist]
### Tasks
- [x] Add attendees list UI
- [x] Add reserve event form
- [x] Write necessary queries for the reservation of event
- [x] Edit Event functionality
- [x] Close reservation functionality
- [ ] cancel reservation
```
