### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by yehiatarek63** [silverkeytech/reserve#4]
```[tasklist]
### Tasks
- [x] Make the styles of the buttons
- [x] Add the paragraphs in the home page with their layout
- [x] Make the design responsive
```

**Comment by Chetan-KK** [comment]
do you want to make login page responsive?

**Comment by YoussefDarwishh** [comment]
Made the homepage with the styling. Requires to use the correct font that was on the penpot design.
It is not responsive yet

**Comment by Chetan-KK** [comment]
okk i could make it responsive
