### ISSUE TITLE
Event creation

### ISSUE THREAD

**Issue by yehiatarek63** [silverkeytech/reserve#5]
```[tasklist]
### Tasks
- [x] Add the event form UI
- [x] write the necessary APIs and queries
- [x] send email functionality after creation
- [ ] Manipulation of tags field for effective storage and usage
- [x] Enforce jpeg and png validation on image attachment
- [ ] Null exception if tags is left empty even though it is optional
```
