### ISSUE TITLE
Queue creation

### ISSUE THREAD

**Issue by yehiatarek63** [silverkeytech/reserve#6]
```[tasklist]
### Tasks
- [ ] Add queue creation form
- [ ] Write necessary APIs for queue creation, queue served
- [ ] Implement reset functionality
```

**Comment by YoussefDarwishh** [comment]
Finished UI for the other pages after queue creation form.
Will start next on writing the necessary queries/api endpoints.

**Comment by YoussefDarwishh** [comment]
Made the endpoints to:

- Create a queue Event
- Get queue details by ID
- Get the next customer queue number (i think this could be useless if i can get details of queue)
- Register customer "queue up"
- Serve customer
- Reset Queue

These were written but not tested yet.
