### ISSUE TITLE
Fixing Existing Bugs

### ISSUE THREAD

**Issue by amiraelgarf** [silverkeytech/reserve#66]
```[tasklist]
### Tasks
- [x] Appointment button redirect to nothing
- [x] No email gets send when creating event/email/calender
- [x] Validate on the start date. it can't be before the date that I am currently in
- [x] Appoinment and queue doesn't has error logging
- [x] Reserving an appointment doesn't work as intended
```

**Comment by dodyg** [comment]
@amiraelgarf  write and capitalize properly. 

![image](https://github.com/silverkeytech/reserve/assets/1761249/0ba9a365-1545-4f5f-a3f3-89c17162615a)

**Comment by amiraelgarf** [comment]
All bugs are resolved
