### ISSUE TITLE
Enhancements for the code

### ISSUE THREAD

**Issue by amiraelgarf** [silverkeytech/reserve#68]
```[tasklist]
### Tasks
- [x] Adding antiforgery middleware
- [x] Creating polling for the tables
- [x] Added email service to appointment creation
```
