### ISSUE TITLE
Event creation notification and details UI

### ISSUE THREAD

**Issue by yehiatarek63** [silverkeytech/reserve#8]
```[tasklist]
### Tasks
- [x] Add notification page with the links that the event creator will need
- [x] apply the PenPot UI to notification page
- [x] Make the event details UI by applying PenPot styles
```
